<a href="https://colab.research.google.com/github/veniapputrii/Python/blob/Introduction/Python_Anf%C3%A4nger.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#heute lerne ich am 28.Jan
#impotiere das Werkzeug 'Pandas'
import pandas as pd

#erstelle einfache Daten (ein Wörterbuch)
daten = {
    'Name' : ['Anna', 'Bob', 'Charlie', 'David', 'Eva'],
    'Alter': [24, 30, 22, 35, 30],
    'Stadt': ['Berlin', 'München', 'Hamburg', 'Köln', 'Frankfurt'],
    'Gehalt': [6000, 4200, 2800, 3400, 1300]
}

#handle die Daten in eine Tabelle um (einen 'DateFrame')
df = pd.DataFrame(daten)

#Zeige die ersten Zeilen an
print('hier ist deine Tabelle:')
display(df)

#eine erste kleine Analyse: wie hoch ist das Durchschnittsgehalt?
durchschnitt = df['Gehalt'].mean()
print(f'\nDas Durchschnittliche Gehalt beträgt: {durchschnitt} Euro')

hier ist deine Tabelle:

      Name  Alter      Stadt  Gehalt
0     Anna     24     Berlin    6000
1      Bob     30    München    4200
2  Charlie     22    Hamburg    2800
3    David     35       Köln    3400
4      Eva     30  Frankfurt    1300

Das Durchschnittliche Gehalt beträgt: 3540.0 Euro

In [ ]:
#30.Jan
#erstelle einen Filter und
#beachte das doppelte Gleichheitszeichen (==)

filter_bedigung = df['Stadt'] == 'Berlin'

#wir wenden den Filter auf die Tabelle an
berliner = df[filter_bedigung]

#ergebnis anzeigen
display(berliner)

   Name  Alter   Stadt  Gehalt
0  Anna     24  Berlin    6000

In [ ]:
#30. Jan
#noch einmal machen, aber 'Alter'
filterA = df['Alter'] >= 30

#noch einmal wenden auf di Tabelle an
Alter = df[filterA]

#Ergebnis von Alter anzeigen
display(Alter)

    Name  Alter      Stadt  Gehalt
1    Bob     30    München    4200
3  David     35       Köln    3400
4    Eva     30  Frankfurt    1300

In [ ]:
#31. Jan 2026
#neue Aufgabe trainieren
import pandas as pd
#Unsere Daten : Produktname, Preis (im Euro), und aktueller Bestand
shop_Daten = {
    'Produkt' : ['Laptop', 'Maus', 'Tastatur', 'Monitor', 'USB-Stick'],
    'Preis' : [999.99, 29.99, 79.99, 19,12],
    'Bestand' : [10, 2, 15, 5, 0]
}

#Tabelle erstellen
df1 = pd.DataFrame(shop_Daten)


#zeige die Tabelle
display(df1)

     Produkt   Preis  Bestand
0     Laptop  999.99       10
1       Maus   29.99        2
2   Tastatur   79.99       15
3    Monitor   19.00        5
4  USB-Stick   12.00        0

In [ ]:
#1 Feb. 2026
#meine Aufgabe : Welche Produkte sind ausverkauft?
#Ziel : Zeige nur die Zeilen an, wo der Bestand gleich 0 ist.

filterBestand = df1['Bestand'] == 0
neueBestand = df1[filterBestand]

display(neueBestand)

     Produkt  Preis  Bestand
4  USB-Stick   12.0        0

In [ ]:
#1. Feb 2026 01:48
#neue Aufgabe
# Finde alle Produkte, die :
#1. Weniger als 50 Euro (<50)
#UND (&)
#Noch auf Lager sind (also Bestand > 0)
filterPreis = df1['Preis'] < 50
filterBestand = df1['Bestand'] > 0

ergebnis = df1[ filterPreis & filterBestand ] #auf die Tabelle, die df1 ist, autragen
display(ergebnis)

   Produkt  Preis  Bestand
1     Maus  29.99        2
3  Monitor  19.00        5

In [ ]:
#1. Feb 2026
#versuche ich Preis unter 20 und Bestand über 0
# speichere das Ergebnis in der Variable 'schnaaeppchen'

filterPreis = df1['Preis'] < 20
filterBestand = df1['Bestand'] > 0
schnaeppchen = df1[ filterPreis & filterBestand ] #auf die Tabelle, die df1 ist, autragen
display(schnaeppchen)

   Produkt  Preis  Bestand
3  Monitor   19.0        5

In [ ]:
#Wir wollen wissen : Wie viel Geld liegt in unserem Lager? Lager = warehouse?
#Rechnung : Preis mal Bestand

df1['Lagerwert'] = df1['Preis'] * df1['Bestand']
display(df1)

     Produkt   Preis  Bestand  Lagerwert
0     Laptop  999.99       10    9999.90
1       Maus   29.99        2      59.98
2   Tastatur   79.99       15    1199.85
3    Monitor   19.00        5      95.00
4  USB-Stick   12.00        0       0.00

In [ ]:
#2.Feb 2026
#Aufgabe :
# Wir wollen einen Schlussverkauf machen. Alle Produkte sollen um die Hälfte
#reduziert werden. Erstelle eine neue Spalte namens 'Sale_Preis'.
#Der Inhalt soll der 'Preis' geteilt durch 2 sein.
#Tipp: Das Zeichen für Teilen ist der Schrägstrich (/).

df1['Sale_Preis'] = df1['Preis'] / 2
display(df1)

     Produkt   Preis  Bestand  Lagerwert  Sale_Preis
0     Laptop  999.99       10    9999.90     499.995
1       Maus   29.99        2      59.98      14.995
2   Tastatur   79.99       15    1199.85      39.995
3    Monitor   19.00        5      95.00       9.500
4  USB-Stick   12.00        0       0.00       6.000

In [ ]:
#probiere ich noch einmal darüber aus.
df1['Neue Bestand'] = df1['Bestand'] / 2
display(df1)

     Produkt   Preis  Bestand  Lagerwert  Sale_Preis  Neue Bestand
0     Laptop  999.99       10    9999.90     499.995           5.0
1       Maus   29.99        2      59.98      14.995           1.0
2   Tastatur   79.99       15    1199.85      39.995           7.5
3    Monitor   19.00        5      95.00       9.500           2.5
4  USB-Stick   12.00        0       0.00       6.000           0.0

In [ ]:
#2. Feb 2026
#Ich möchte die 'Neue Bestand' Spalte entfernen

df1 = df1.drop('Neue Bestand', axis=1)
display(df1)

     Produkt   Preis  Bestand  Lagerwert  Sale_Preis
0     Laptop  999.99       10    9999.90     499.995
1       Maus   29.99        2      59.98      14.995
2   Tastatur   79.99       15    1199.85      39.995
3    Monitor   19.00        5      95.00       9.500
4  USB-Stick   12.00        0       0.00       6.000

In [ ]:
#3.Feb 2026
#Das Konzept : Sortieren
#Meine Aufgabe : Kann ich die Tabelle so sortieren, dass wir sehen, von welchem Produkt
#wir am wenigsten auf Lager haben?
#Wir wollen nach der Spalte 'Bestand' sortieren.
#Wir wollen aufsteigend sortieren (von 0 bis ...), also die kleinsten Zahlen zuerst.

df_sortiert = df1.sort_values(by='Bestand', ascending = False) #False = es sieht das Gegenteil der gewünschten Zahl
#aber 'True' ist direkt die Zahlen zu schauen
display(df_sortiert)

     Produkt   Preis  Bestand  Lagerwert  Sale_Preis
2   Tastatur   79.99       15    1199.85      39.995
0     Laptop  999.99       10    9999.90     499.995
3    Monitor   19.00        5      95.00       9.500
1       Maus   29.99        2      59.98      14.995
4  USB-Stick   12.00        0       0.00       6.000

In [ ]:
#4. Februar 2026
#Ich hab' Aggregation (Zusammenfassen) gelernt
#Meine Aufgaben : Berechne die Gesamtzahl aller Artikel im Lager.
#1. Wähle die Spalte 'Bestand' aus
#2. Hänge.sum() hinten dran.

gesamtzahl = df1['Bestand'].sum() #Richtig : Spalte wählen > Punkt > Funtoin
print('Gesamtanzahl im Lager:', gesamtzahl)

Gesamtanzahl im Lager: 32

In [ ]:
#5.Februar 2026
#Frage : Wenn du statt der Summe den durchschnittlichen Preis
#wissen wolltest.. wie müsste der Code dann heißen?
gewöhnlichePreis = df1['Preis'].mean()
print('der durchschnittliche Preis is :', gewöhnlichePreis)

der durchschnittliche Preis is : 228.19400000000002

In [ ]:
#Das nächste Level : Gruppieren
#wir brauchen zu erst Kategorien
#und Wir fügen eine Kategorie hinzu, damit wir gleich gruppieren können
df1['Kategorie'] = ['Elektronik', 'Zubehör', 'Zubehör', 'Elektronik', 'Zubehör']
display(df1)

     Produkt   Preis  Bestand  Lagerwert  Sale_Preis   Kategorie
0     Laptop  999.99       10    9999.90     499.995  Elektronik
1       Maus   29.99        2      59.98      14.995     Zubehör
2   Tastatur   79.99       15    1199.85      39.995     Zubehör
3    Monitor   19.00        5      95.00       9.500  Elektronik
4  USB-Stick   12.00        0       0.00       6.000     Zubehör

In [ ]:
#Meine Aufgabe
#Jetzt wollen wir wisen : Was ist der durchschnittliche Preis pro. Kategorie?
Gruppieren = df1.groupby('Kategorie')['Preis'].mean()
display(Gruppieren)

Kategorie
Elektronik    509.495
Zubehör        40.660
Name: Preis, dtype: float64

In [ ]:
schöneGruppieren = df1.groupby('Kategorie')['Preis'].mean().reset_index()
display(schöneGruppieren)

    Kategorie    Preis
0  Elektronik  509.495
1     Zubehör   40.660

In [ ]:
#Meine letzte Prüfung
#Jetzt kombiniere ich alles.
#Der Chef will wissen :
#Wie viele Produkte haben wir in jeder Kategorie ingesamt
#auf Lager?
#Ich muss :
#Nach 'Kategorie' gruppieren.
#Die Spalte 'Bestand' auswählen (statt Preis).
#Die Summe .sum() berechnen (statt Durchschnitt).
#(Optional).reset_index() nutzen, damit es hübsch aussieht.

display(df1)
neueAufgabe = df1.groupby('Kategorie')['Bestand'].sum().reset_index()
display(neueAufgabe)

     Produkt   Preis  Bestand  Lagerwert  Sale_Preis   Kategorie
0     Laptop  999.99       10    9999.90     499.995  Elektronik
1       Maus   29.99        2      59.98      14.995     Zubehör
2   Tastatur   79.99       15    1199.85      39.995     Zubehör
3    Monitor   19.00        5      95.00       9.500  Elektronik
4  USB-Stick   12.00        0       0.00       6.000     Zubehör

    Kategorie  Bestand
0  Elektronik       15
1     Zubehör       17