<a href="https://colab.research.google.com/github/veniapputrii/Python/blob/Introduction/Python_Anf%C3%A4nger.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#heute lerne ich am 28.Jan
#impotiere das Werkzeug 'Pandas'
import pandas as pd

#erstelle einfache Daten (ein Wörterbuch)
daten = {
    'Name' : ['Anna', 'Bob', 'Charlie', 'David', 'Eva'],
    'Alter': [24, 30, 22, 35, 30],
    'Stadt': ['Berlin', 'München', 'Hamburg', 'Köln', 'Frankfurt'],
    'Gehalt': [6000, 4200, 2800, 3400, 1300]
}

#handle die Daten in eine Tabelle um (einen 'DateFrame')
df = pd.DataFrame(daten)

#Zeige die ersten Zeilen an
print('hier ist deine Tabelle:')
display(df)

#eine erste kleine Analyse: wie hoch ist das Durchschnittsgehalt?
durchschnitt = df['Gehalt'].mean()
print(f'\nDas Durchschnittliche Gehalt beträgt: {durchschnitt} Euro')

hier ist deine Tabelle:

      Name  Alter      Stadt  Gehalt
0     Anna     24     Berlin    6000
1      Bob     30    München    4200
2  Charlie     22    Hamburg    2800
3    David     35       Köln    3400
4      Eva     30  Frankfurt    1300

Das Durchschnittliche Gehalt beträgt: 3540.0 Euro

In [ ]:
#30.Jan
#erstelle einen Filter und
#beachte das doppelte Gleichheitszeichen (==)

filter_bedigung = df['Stadt'] == 'Berlin'

#wir wenden den Filter auf die Tabelle an
berliner = df[filter_bedigung]

#ergebnis anzeigen
display(berliner)

   Name  Alter   Stadt  Gehalt
0  Anna     24  Berlin    6000

In [ ]:
#30. Jan
#noch einmal machen, aber 'Alter'
filterA = df['Alter'] >= 30

#noch einmal wenden auf di Tabelle an
Alter = df[filterA]

#Ergebnis von Alter anzeigen
display(Alter)

    Name  Alter      Stadt  Gehalt
1    Bob     30    München    4200
3  David     35       Köln    3400
4    Eva     30  Frankfurt    1300

In [2]:
#31. Jan 2026
#neue Aufgabe trainieren
import pandas as pd
#Unsere Daten : Produktname, Preis (im Euro), und aktueller Bestand
shop_Daten = {
    'Produkt' : ['Laptop', 'Maus', 'Tastatur', 'Monitor', 'USB-Stick'],
    'Preis' : [999.99, 29.99, 79.99, 19,12],
    'Bestand' : [10, 2, 15, 5, 0]
}

#Tabelle erstellen
df1 = pd.DataFrame(shop_Daten)


#zeige die Tabelle
display(df1)

     Produkt   Preis  Bestand
0     Laptop  999.99       10
1       Maus   29.99        2
2   Tastatur   79.99       15
3    Monitor   19.00        5
4  USB-Stick   12.00        0

In [3]:
#1 Feb. 2026
#meine Aufgabe : Welche Produkte sind ausverkauft?
#Ziel : Zeige nur die Zeilen an, wo der Bestand gleich 0 ist.

filterBestand = df1['Bestand'] == 0
neueBestand = df1[filterBestand]

display(neueBestand)

     Produkt  Preis  Bestand
4  USB-Stick   12.0        0

In [4]:
#1. Feb 2026 01:48
#neue Aufgabe
# Finde alle Produkte, die :
#1. Weniger als 50 Euro (<50)
#UND (&)
#Noch auf Lager sind (also Bestand > 0)
filterPreis = df1['Preis'] < 50
filterBestand = df1['Bestand'] > 0

ergebnis = df1[ filterPreis & filterBestand ] #auf die Tabelle, die df1 ist, autragen
display(ergebnis)

   Produkt  Preis  Bestand
1     Maus  29.99        2
3  Monitor  19.00        5

In [7]:
#1. Feb 2026
#versuche ich Preis unter 20 und Bestand über 0
# speichere das Ergebnis in der Variable 'schnaaeppchen'

filterPreis = df1['Preis'] < 20
filterBestand = df1['Bestand'] > 0
schnaeppchen = df1[ filterPreis & filterBestand ] #auf die Tabelle, die df1 ist, autragen
display(schnaeppchen)

   Produkt  Preis  Bestand
3  Monitor   19.0        5

In [8]:
#Wir wollen wissen : Wie viel Geld liegt in unserem Lager?
#Rechnung : Preis mal Bestand

df1['Lagerwert'] = df1['Preis'] * df1['Bestand']
display(df1)

     Produkt   Preis  Bestand  Lagerwert
0     Laptop  999.99       10    9999.90
1       Maus   29.99        2      59.98
2   Tastatur   79.99       15    1199.85
3    Monitor   19.00        5      95.00
4  USB-Stick   12.00        0       0.00